In [5]:
'''Chapter 13
Tensors and Tensor Arithmetic
In deep learning it is common to see a lot of discussion around tensors as the cornerstone
data structure. Tensor even appears in name of Google’s flagship machine learning library:
TensorFlow. '''
'''13.2 What are Tensors
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional
array.'''
# 13.3 Tensors in Python
from numpy import array
T = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [6]:
# 13.4.1 Tensor Addition
from numpy import array

# define first tensor
A = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

# define second tensor
B = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

# add tensors
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [8]:
# 13.4.2 Tensor Subtraction
from numpy import array

# define first tensor
A = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

# define second tensor
B = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])

# substract tensors
C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [10]:
# 13.4.3 Tensor Hadamard Product
'''As with matrices, the operation is referred to
as the Hadamard Product to differentiate it from tensor multiplication.'''
# C = A ◦ B
# tesnor harmard product
from numpy import array

# define first tensor
A = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])
print(A)

B = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])
print(B)

C = A * B
print(C)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [13]:
# 13.4.4 Tensor Division
from numpy import array

# define first tensor
A = array([
    [[1,2,3], [4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])
print(A)

# define second tensor
B = array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
])
print(B)

C = A / B
print(C)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
# 13.5 Tensor Product
'''The tensor product can be implemented in NumPy using the tensordot() function. The
function takes as arguments the two tensors to be multiplied and the axis on which to sum the
products over, called the sum reduction. To calculate the tensor product, also called the tensor
dot product in NumPy, the axis must be set to 0. In the example below, we define two order-1
tensors (vectors) with and calculate the tensor product.'''

from numpy import array
from numpy import tensordot
# we define two order-1 tensors

# define first vector
A = array([1,2])

# define second vector
B = ([3,4])

# calculate tensor product 
C = tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]


In [31]:
'''13.6 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
13.7. Further Reading 106
ˆ Update each example using your own small contrived tensor array data.
ˆ Implement three other types of tensor multiplication not covered in this tutorial with
small vector or matrix data.
ˆ Write your own functions to implement each tensor arithmetic operation.'''

T1 = array([
    [[2,4,8],[16,32,64],[128,256,512]],
    [[1024,2048,4096],[8192,16384,32768],[65436,13872,26744]],
    [[53488,106976,113952],[227904,455808,911616], [1823232, 3646464, 7292928]]
])
T2 = array([
    [[2,4,8],[16,32,64],[128,256,512]],
    [[1024,2048,4096],[8192,16384,32768],[65436,13872,26744]],
    [[53488,106976,113952],[227904,455808,911616], [1823232, 3646464, 7292928]]
])

print(T1.shape)
print(T2.shape)

# addition 
T = T1 + T2
print(T)

# substraction
T = T1 - T2
print(T)

# harmard product
T = T1 * T2
print(T)

# division
T = T1 / T2
print(T)

# tensor product
T = tensordot(T1, T2, axes=0)
print('tensordot\n\n',T)

# https://en.wikipedia.org/wiki/Tensor

(3, 3, 3)
(3, 3, 3)
[[[       4        8       16]
  [      32       64      128]
  [     256      512     1024]]

 [[    2048     4096     8192]
  [   16384    32768    65536]
  [  130872    27744    53488]]

 [[  106976   213952   227904]
  [  455808   911616  1823232]
  [ 3646464  7292928 14585856]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[             4             16             64]
  [           256           1024           4096]
  [         16384          65536         262144]]

 [[       1048576        4194304       16777216]
  [      67108864      268435456     1073741824]
  [    4281870096      192432384      715241536]]

 [[    2860966144    11443864576    12985058304]
  [   51940233216   207760932864   831043731456]
  [ 3324174925824 13296699703296 53186798813184]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
tensordot

 [[[[[[           