In [4]:
# 14.2 What is a Matrix Decomposition
'''A matrix decomposition is a way of reducing a matrix into its constituent parts. It is an
approach that can simplify more complex matrix operations that can be performed on the
decomposed matrix rather than on the original matrix itself.'''

# 14.3 LU Decomposition
# The LU decomposition is for square matrices and decomposes a matrix into L and U components
# A = L · U
# A is the square matrix that we wish to decompose, L is the lower triangle matrix
# and U is the upper triangle matrix.

'''A = L · U · P => LUP decomposition, or the LU decomposition with partial pivoting
The rows of the parent matrix are re-ordered to simplify the decomposition process and the
additional P matrix specifies a way to permute the result or return the result to the original
order'''

# LU decomposition
from numpy import array
from scipy.linalg import lu

A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)

# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.00000000e+00 8.00000000e+00 9.00000000e+00]
 [0.00000000e+00 8.57142857e-01 1.71428571e+00]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
# 14.4 QR Decomposition
'''The QR decomposition is for n × m matrices (not limited to square matrices) and decomposes
a matrix into Q and R components.
A = Q · R
Where A is the matrix that we wish to decompose, Q a matrix with the size m × m, and R is
an upper triangle matrix with the size m × n.
'''
# QR decomposition
from numpy import array
from numpy.linalg import qr

# define rectangular matrix
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)

# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)

# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [10]:
# 14.5 Cholesky Decomposition
'''The Cholesky decomposition is for square symmetric matrices where all values are greater than
zero, so-called positive definite matrices.
A = L · L^T
Where A is the matrix being decomposed, L is the lower triangular matrix and L
T is the transpose of L.'''

# The decompose can also be written as the product of the upper triangular
# matrix, for example:A = U^T· U

# When you can use it, Cholesky decomposition
# is about a factor of two faster than alternative methods for solving linear equations.

from numpy import array
from numpy.linalg import cholesky

# define symmetrical matrix
A = array([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
print(A)

# factorize
L = cholesky(A)
print(L)

# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [20]:
'''14.6 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Write a summary of matrix decomposition to explain the principle to other students.
ˆ Create one example using each operation with your own small array data.
ˆ Search machine learning papers and find 1 example of each operation being used'''

# Matrix decomposition use to reduce the main matrix in to its contituent parts in order to
# get better performance rather than running original matrix
# There are three types of decomposition methods that we discussed here
# - LU decomposition => Rows of parent matrix reorder (to simplify decompostion process) 
# and additional P metrix added to permute the results and reorder values
# - QR decomposition => use for n x m matrices, dicompose matrix into Q and R components
# - Cholesky decomposition => Use for symmatric matrices where all values > 0, dicompose to Q and R components

A = array([
    [2,4,6],
    [2,4,6]
])
print(A)

# LU
# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)

# reconstruct
B = P.dot(L).dot(U)
print(B)

# QR
# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)

# reconstruct
B = Q.dot(R)
print(B)

# cholesky
A = array([
    [8,8,8],
    [8,8,8],
    [8,8,8]
])
print(A)

# factorize
L = cholesky(A)
print(L)

# reconstruct
B = L.dot(A)
print(B)

[[2 4 6]
 [2 4 6]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [1. 1.]]
[[2. 4. 6.]
 [0. 0. 0.]]
[[2. 4. 6.]
 [2. 4. 6.]]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[[-2.82842712 -5.65685425 -8.48528137]
 [ 0.          0.          0.        ]]
[[2. 4. 6.]
 [2. 4. 6.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[2.82842712e+00 0.00000000e+00 0.00000000e+00]
 [2.82842712e+00 4.21468485e-08 0.00000000e+00]
 [2.82842712e+00 4.21468485e-08 6.28036983e-16]]
[[22.627417   22.627417   22.627417  ]
 [22.62741734 22.62741734 22.62741734]
 [22.62741734 22.62741734 22.62741734]]


In [ ]:
# Search machine learning papers and find 1 example of each operation being used
# https://heartbeat.fritz.ai/applications-of-matrix-decompositions-for-machine-learning-f1986d03571a
Background Removal
Topic Modeling
Recommendations using Collaborative Filtering
Eigen Faces
