In [31]:
# eye-gan
'''Matrix decompositions are a useful tool for reducing a matrix to their constituent parts in
order to simplify a range of more complex operations. '''
# Perhaps the most used type of matrix
# decomposition is the eigendecomposition that decomposes a matrix into eigenvectors and
# eigenvalues.

#  A · v = λ · v
# A is the parent square matrix that we are
# decomposing, v is the eigenvector of the matrix, and λ is the lowercase Greek letter lambda and
# represents the eigenvalue scalar.

'''The parent matrix can be shown
to be a product of the eigenvectors and eigenvalues.
A = Q · Λ · Q^T'''
'''
Eigendecomposition can also be used to calculate the principal components of a matrix in the
Principal Component Analysis method or PCA that can be used to reduce the dimensionality
of data in machine learning.'''


'\nEigendecomposition can also be used to calculate the principal components of a matrix in the\nPrincipal Component Analysis method or PCA that can be used to reduce the dimensionality\nof data in machine learning.'

In [32]:
# 15.4 Calculation of Eigendecomposition
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

# factorize
values, vectors = eig(A)
print(values,'\n')
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15] 

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [33]:
# 15.5 Confirm an Eigenvector and Eigenvalue
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# factorize
values, vectors = eig(A)
print(values)
print(vectors, '\n')

# confirm first eigenvector
B = A.dot(vectors[:,0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]] 

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [34]:
# 15.6 Reconstruct Matrix
'''The eigenvalues need to be arranged into a diagonal matrix. The NumPy
diag() function can be used for this. Next, we need to calculate the inverse of the eigenvector
matrix, which we can achieve with the inv() NumPy function. Finally, these elements need to
be multiplied together with the dot() function.'''

# reconstrunct matrix
from numpy import diag
from numpy.linalg import inv
from numpy.linalg import eig
from numpy import array

# define matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

# factorize
values, vectors = eig(A)
print(values)
print(vectors)

# create matrix from eigenvectors
Q = vectors

# create inv eigenvector matrix
R = inv(Q)

# create diagonal matrix from eigen values
L = diag(values)

# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [44]:
'''15.7 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Develop an eigendecomposition and reconstruction of your own small contrived array data.
ˆ List ten high-level operations that make use of the eigendecomposition.
ˆ Implement the eigendecomposition operation from scratch for matrices defined as lists of
lists.'''

# define matrix
A = array([
    [32,64,128],
    [256,512,1024],
    [2048,4096,8192]
])
print(A)

# factorize
values, vectors = eig(A)
print(values)
print(vectors)

# confirm first eigen vector
B = A.dot(vectors[:,0])
print(B)

C = Q.dot(vectors[:,0]) * values[0]
print(C)

[[  32   64  128]
 [ 256  512 1024]
 [2048 4096 8192]]
[   0. 8736.    0.]
[[-0.97301847  0.01550248  0.        ]
 [ 0.02861819  0.12401983 -0.89442719]
 [ 0.22894552  0.99215863  0.4472136 ]]
[8.88178420e-16 7.10542736e-15 5.68434189e-14]
[ 0. -0. -0.]


In [48]:
# define matrix
A = array([
    [32,64,128],
    [256,512,1024],
    [2048,4096,8192]
])
print(A)

# factorize
values, vectors = eig(A)
print(values)
print(vectors)

# create matrix from eigen vectors
Q = vectors
print(Q)

# create inv matrix from eigen vectors
R = inv(Q)
print(R)

# create diagonal matrix from eigen value
L = diag(values)
print('diagonal\n',L)

# reconstruct the eigen vector
B = Q.dot(L).dot(R)
print(B)

[[  32   64  128]
 [ 256  512 1024]
 [2048 4096 8192]]
[   0. 8736.    0.]
[[-0.97301847  0.01550248  0.        ]
 [ 0.02861819  0.12401983 -0.89442719]
 [ 0.22894552  0.99215863  0.4472136 ]]
[[-0.97301847  0.01550248  0.        ]
 [ 0.02861819  0.12401983 -0.89442719]
 [ 0.22894552  0.99215863  0.4472136 ]]
[[-1.02396514e+00  7.52915544e-03  1.50583109e-02]
 [ 2.36285032e-01  4.72570064e-01  9.45140127e-01]
 [ 3.65078552e-18 -1.05226728e+00  1.31533410e-01]]
diagonal
 [[   0.    0.    0.]
 [   0. 8736.    0.]
 [   0.    0.    0.]]
[[  32.   64.  128.]
 [ 256.  512. 1024.]
 [2048. 4096. 8192.]]


In [ ]:
# List ten high-level operations that make use of the eigendecomposition.
# https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix
# hyper-spectral remote sensing.
# car stereo etc
