In [1]:
# 16.2 What is the Singular-Value Decomposition
# The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
# reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
# simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore
# the case for complex numbers.
# A = U · Σ · V^T

In [3]:
# singular-value decomposition
from numpy import array
from numpy.linalg import svd

# define a matrix
A = array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)

# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [10]:
# U(m × m) · Σ(m × m) · V^T(n × n)
# reconstruct regular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

# define a matrix
A = array([
    [1,2],
    [3,4],
    [5,6]])
print(A)

# factorize
U, s, V = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# print(Sigma)
# polpulate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print('\n',B)

[[1 2]
 [3 4]
 [5 6]]

 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [11]:
'''The above complication with the Σ diagonal only exists with the case where m and n are
not equal. The diagonal matrix can be used directly when reconstructing a square matrix, as
follows.'''

'The above complication with the Σ diagonal only exists with the case where m and n are\nnot equal. The diagonal matrix can be used directly when reconstructing a square matrix, as\nfollows.'

In [14]:
# reconstruct square matrix from svd
from numpy import array
from numpy import diag
from scipy.linalg import svd

# define matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

# factorize
U, s, V = svd(A)

# create n x n sigma matrix
Sigma = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
# The pseudoinverse is denoted as A+, where A is the matrix that is being inverted and + is a
# superscript. The pseudoinverse is calculated using the singular value decomposition of A:
# A^+ = V · D^+ · U^T

# Where A+ is the pseudoinverse, D+ is the pseudoinverse of the diagonal matrix Σ and V
# T  is the transpose of V T. We can get U and V from the SVD operation.
# A = U · Σ · V^T

# pseudoinverse
from numpy import array
from scipy.linalg import pinv

# define array
A = array([
    [0.1,0.2],
    [0.3,0.4],
    [0.5,0.6],
    [0.7,0.8]
])
print(A)

# calculate pseudoinverse
B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.31262171e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [19]:
'''We can calculate the pseudoinverse manually via the SVD and compare the results to the
pinv() function. First we must calculate the SVD. Next we must calculate the reciprocal of
each value in the s array. Then the s array can be transformed into a diagonal matrix with an
added row of zeros to make it rectangular. Finally, we can calculate the pseudoinverse from the
elements. The specific implementation is:
A^+ = V^T · D^T · U^T'''

# pseudoinverse via SVD
from numpy import array 
from numpy.linalg import svd
from numpy import zeros
from numpy import diag

# define matrix
A = array([
    [0.1,0.2],
    [0.3,0.4],
    [0.5,0.6],
    [0.7,0.8]
])
print(A)

# factorize
U, s, V = svd(A)

# reciporcals of s
d = 1.0 / s

# create m x n D matrix
D = zeros(A.shape)

# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] =  diag(d)

# calculate pseudoinverse
B = V.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.28508315e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]
