In [3]:
# vector mean
from numpy import array
from numpy import mean

# define vector
v = array([1,2,3,4,5,6])
print(v)

# calculate mean
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [4]:
# matrix means
from numpy import array
from numpy import mean

# define matrix
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(M)

# col means
col_means = mean(M, axis=)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
