In [130]:
# vector mean
from numpy import array
from numpy import mean

# define vector
v = array([1,2,3,4,5,6])
print(v)

# calculate mean
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [131]:
# matrix means
from numpy import array
from numpy import mean

# define matrix
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(M)

# col means
col_meacn = mean(M, axis=0)
print(col_mean)

# row means
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


In [132]:
# vector variance
from numpy import array
from numpy import var

# define vector
v = array([1,2,3,4,5,6])
print(v)

# population variance
result = var(v)
print(result)

# sample variance
result = var(v, ddof=1)
print(result)

[1 2 3 4 5 6]
2.9166666666666665
3.5


In [133]:
# matrix variances
from numpy import array
from numpy import var

# define matrix
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
print(M)

# col variance
col_variance = var(M, ddof=1, axis=0)
print(col_variance)

# row variance
row_variance = var(M, ddof=1, axis=1)
print(row_variance)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


In [134]:
# matrix standard deviation
from numpy import array
from numpy import std

# define matrix
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])

# col std
col_std = std(M, ddof=1, axis=0)
print(col_std)

# row std
row_std = std(M, ddof=1, axis=1)
print(row_std)

[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


In [135]:
# vector covariance
from numpy import array
from numpy import cov

# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)

# define second vector
y = array([9,8,7,6,5,4,3,2,1])
print(y)

# calculate covariance
Sigma = cov(x, y)[0,1]
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


In [136]:
# vector correlation
from numpy import array
from numpy import corrcoef

# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)

# define second vector
y = array([9,8,7,6,5,4,3,2,1])
print(y)

# calculate correlation
corr = corrcoef(x, y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-1.0


In [137]:
# covariance matrix
from numpy import array
from numpy import cov

# define matrix of observations
X = array([
    [1,5,8],
    [3,5,11],
    [2,4,9],
    [3,6,10],
    [1,5,10]
])
print(X)

# calculate covariance matrix
Sigma = cov(X.T)
print(Sigma)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]


In [138]:
'''17.6 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Explore each example using your own small contrived array data.
ˆ Load data from a CSV file and apply each operation to the data columns.
ˆ Write your own functions to implement each statistical operation'''

# calculate vector mean
A = array([2,4,6,8,10,12,14,16])
print(mean(A))

# calculate matrix mean
M = array([[2,4,8,16],
         [32,64,128,254]])

# col mean
print(mean(M, axis=0))

# row mean
print(mean(M, axis=1))

# vector variance
V = array([5,25,125,625])
print(var(V, ddof=1)) # population variance

# matrix variance
A = array([
    [2,4,8,16],
    [2,4,8,16]
])
# col variance
print(var(A, axis=0, ddof=1))

# row variance
print(var(A, axis=1, ddof=1))

# matrix std
A = array([
    [11,22,33,44,55,66],
    [66,55,44,33,22,11]
])

# col std
print(std(A, axis=0, ddof=1))

# row std
print(std(A, axis=1, ddof=0))


# vector covariance
X = array([4,16,64,128,256,512])
Y = array([512,256,128,64,16,4])

Sigma = cov(X,Y)[0,1]
print(Sigma)

# vector correlation 
Sigma = corrcoef(X,Y)[0,1]
print(Sigma)

# matrix covariance
M = array([[999,888,777],
         [666,555,444],
         [333,222,111]])

Sigma = cov(M.T)
print(Sigma)

9.0
[ 17.  34.  68. 135.]
[  7.5 119.5]
84933.33333333333
[0. 0. 0. 0.]
[38.33333333 38.33333333]
[38.89087297 23.33452378  7.77817459  7.77817459 23.33452378 38.89087297]
[18.7860764 18.7860764]
-26278.933333333334
-0.6975522743038352
[[110889. 110889. 110889.]
 [110889. 110889. 110889.]
 [110889. 110889. 110889.]]


In [175]:
# Load data from a CSV file and apply each operation to the data columns.
url = 'ex17.csv'
names = ['col1', 'col2', 'col3', 'col4', 'col5', 'col6']
dataset = pd.read_csv(url, names=names)
dataset.head()

col1  col2  col3  col4  col5  col6
0    10    20    30    40    50    60
1    60    50    40    30    20    10

In [176]:
# calculate vector mean
print(mean(dataset))

col1    35.0
col2    35.0
col3    35.0
col4    35.0
col5    35.0
col6    35.0
dtype: float64


In [177]:
# calculate matrix mean
# col mean
col_mean = mean(dataset, axis=0)
print(col_mean)

# row mean
row_mean = mean(dataset, axis=1)
print(row_mean)

col1    35.0
col2    35.0
col3    35.0
col4    35.0
col5    35.0
col6    35.0
dtype: float64
0    35.0
1    35.0
dtype: float64


In [178]:
# vector variance - sample
result = var(dataset.iloc[1], ddof=1)
print(result)

# vector variance - population
result = var(dataset.iloc[1])
print(result)

# matrix variances
# col variance
col_var = var(dataset, axis=0)
print(col_var)

# row variance
row_var = var(dataset, axis=1)
print(row_var)

350.0
291.6666666666667
col1    625.0
col2    225.0
col3     25.0
col4     25.0
col5    225.0
col6    625.0
dtype: float64
0    291.666667
1    291.666667
dtype: float64


In [179]:
# matrix std
# col std
col_std = std(dataset, axis=0)
print(col_std)

# row std
row_std = std(dataset, axis=1)
print(row_std)

col1    25.0
col2    15.0
col3     5.0
col4     5.0
col5    15.0
col6    25.0
dtype: float64
0    17.078251
1    17.078251
dtype: float64


In [183]:
# vector covariance
X = dataset.iloc[0]
y = dataset.iloc[1]

Sigma = cov(X,y)[0,1]
print(Sigma)

# vector corelation
Sigma = corrcoef(X,y)[0,1]
print(Sigma)

-350.0
-0.9999999999999998


In [185]:
# matrix covariance
Sigma = cov(dataset.T)
print(Sigma)

[[ 1250.   750.   250.  -250.  -750. -1250.]
 [  750.   450.   150.  -150.  -450.  -750.]
 [  250.   150.    50.   -50.  -150.  -250.]
 [ -250.  -150.   -50.    50.   150.   250.]
 [ -750.  -450.  -150.   150.   450.   750.]
 [-1250.  -750.  -250.   250.   750.  1250.]]
