In [9]:
# 5.2.1 One-Dimensional List to Array
# create one-dimnentional array
from numpy import array
# list of data
data = [11,22,33,44,55]
# array or data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [10]:
# 5.2.2 Two-Dimensional List of Lists to Array
# create two-dimensional array
from numpy import array
# list of data
data = [[11,22],
       [33,44],
       [55,66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [11]:
# 5.3.1 One-Dimensional Indexing
# index a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
# index data
print(data[0])
print(data[4])
# print(data[5]) # value is too large for the bound of array
'''IndexError: index 5 is out of bounds for axis 0 with size 5'''

# negative array indexing
print(data[-1])
print(data[-5])

11
55
55
11


In [12]:
# 5.3.2 Two-Dimensional Indexing
# index two-dimensional array
from numpy import array
# define array
data = array([[11,22],
             [33,44],
             [55,66]])
# index data
print(data[0,0])

# If we are interested in all items in the first row, we could leave the second dimension index
# empty
print(data[0])

11
[11 22]


In [13]:
# 5.4.1 One-Dimensional Slicing
# The slice extends from the from index and ends one item before the to index.
# slice a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[:]) # => print all elements

# slice a subset of a one-dimensional array
print(data[0:1])

# negative slicing of a one-dimensional array
print(data[-2:])

# split input and output data
# define array
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])
# seperate data
X, y = data[:, :-1], data[:, -1]
print('\n',X)
print(y,'\n')

# split train and test data
from numpy import array
# seperate data
split = 2
train, test = data[:split,:], data[split:,:]
print(train, test)

[11 22 33 44 55]
[11]
[44 55]

 [[11 22]
 [44 55]
 [77 88]]
[33 66 99] 

[[11 22 33]
 [44 55 66]] [[77 88 99]]


In [21]:
# 5.5.1 Data Shape
# shape of one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data.shape)

# shape of two-dimensional array
data = array([[11,22],
            [33,44],
            [55,66]])
print(data.shape)

# row and column shape of two-dimensional array
# list of data
data = [[11,22],
       [33,44],
       [55,66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Columns: %d' % data.shape[1])

(5,)
(3, 2)
Rows: 3
Columns: 2


In [26]:
# 5.5.2 Reshape 1D to 2D Array
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data.shape,'\n')

# reshape
data = data.reshape(data.shape[0],1)
print(data.shape)

(5,) 

(5, 1)


In [28]:
# 5.5.3 Reshape 2D to 3D Array
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11,22],
       [33,44],
       [55,66]]
# array of data
data = array(data)
print(data.shape)

# reshape
data = data.reshape(data.shape[0], data.shape[1],1)
print(data.shape)

(3, 2)
(3, 2, 1)


In [48]:
'''5.6 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Develop one example of indexing, slicing and reshaping your own small data arrays.
ˆ Load a small real dataset from CSV file and split it into input and output elements
ˆ Load a small real dataset from CSV file and split it into train and test elements.'''
from numpy import array
data = [[10,100,1000],[20,200,2000],[30,300,3000],[40,400,4000],[50,500,5000]]
data = array(data)
print(data)

# indexing 
print('\n',data[0])
print(data[-5])
print(data[-1])
print(data[-1][0])

# ˆ Load a small real dataset from CSV file and split it into input and output elements

import pandas as pd

url = '../pyTutes/datasets/suv_predictions.csv'
names = ['User ID', 'Gender', 'Age', 'Estimated Salary', 'Purchased']
dataset = pd.read_csv(url, names = names)

# seperate data
X, y = data[:,-1], data[:,1]
print(X, y)

# split train and test data
split = 2
train, test = data[:split, :], data[split:, :]
print(train,'\n', test)

[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]
 [  50  500 5000]]

 [  10  100 1000]
[  10  100 1000]
[  50  500 5000]
50
[1000 2000 3000 4000 5000] [100 200 300 400 500]
[[  10  100 1000]
 [  20  200 2000]] 
 [[  30  300 3000]
 [  40  400 4000]
 [  50  500 5000]]
