In [10]:
# 6.4.1 Scalar and One-Dimensional Array
# broadcast scalar to 1D array
from numpy import array
# define array
a = array([1,2,3])
print(a)

# define scalar
b = 2
print(b)

# broadcast 
c = a + b
print(c, '\n')

# broadcast scalar to 2D array
from numpy import array
# define array
A = array([[1,2,3],
         [1,2,3]])
print(A)

# define scalar
b = 2
print(b)

# broadcast
c = A + b
print(c)

# broadcast 1D array to 2D array
from numpy import array
# define 2D array
A = array([[1,2,3],
          [1,2,3]])
print(A)

# define 1D array
b = array([1,2,3])

# broadcast
C =  A + b
print(C)

[1 2 3]
2
[3 4 5] 

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]
[[1 2 3]
 [1 2 3]]
[[2 4 6]
 [2 4 6]]


In [15]:
# 6.5 Limitations of Broadcasting
# broadcasting error
from numpy import array
# define 2D array
A = array([[1,2,3],
         [1,2,3]])
print(A.shape)

# define 1D array
b = array([1,2])
print(b.shape)

# attempt to broadcast
C = A + b
print(C)

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [19]:
'''6.6 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Create three new and different examples of broadcasting with NumPy arrays.
ˆ Implement your own broadcasting function for manually broadcasting in one and twodimensional cases.
ˆ Benchmark NumPy broadcasting and your own custom broadcasting functions with one
and two dimensional cases with very large arrays.'''

from numpy import array

# define 2D array
A = array([[111,222,333,444],
         [555,666,777,888]])

#define scalar
b = 0.1

# broadcast
C = A + b
print(C)

# ----------------

# define 3D array
A = array([[10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]])
# define 1D array
b = array([1,2,3,4])

# broadcast
C = A + b
print(C)

# ----------------

# define 3D array
A = array([[0.1,0.2,0.3,0.4],
         [0.5,0.6,0.7,0.8],
         [0.9,1.0,1.1,1.2]])
# define 2D array
b = array([[1,2,3,4],
         [1,2,3,4]])

C = A + b
print(C)

[[111.1 222.1 333.1 444.1]
 [555.1 666.1 777.1 888.1]]
[[ 11  22  33  44]
 [ 51  62  73  84]
 [ 91 102 113 124]]


ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 