In [1]:
# 7.3 Defining a Vector
# create a vector
from numpy import array

# define a vector
v = array([1,2,3])
print(v)

[1 2 3]


In [2]:
# 7.4.1 Vector Addition
from numpy import array

# define first vector
a = array([1,2,3])
print(a)

# define second vector
b = array([1,2,3])
print(b)

# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [5]:
# 7.4.2 Vector Subtraction
from numpy import array

# define first vector
a = array([1,2,3])
print(a)

# define second vector
b = array ([0.5,0.5,0.5])
print(b)

# substraction
c = a - b
d = b - a

print(c)
print(d)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]
[-0.5 -1.5 -2.5]


In [9]:
# 7.4.3 Vector Multiplication
from numpy import array

# define first vector
a = array([1,2,3])
print(a)

# define second vector
b = array([1,2,3])
print(b)

# multiply vectors
c = a * b
d = a ** b
print(c)
print(d)

[1 2 3]
[1 2 3]
[1 4 9]
[ 1  4 27]


In [14]:
# 7.4.4 Vector Division
from numpy import array

# define first vector
a = array([1,2,3])
print(a)

# define second vector
b = array([1,2,3])

d = array([4,16,25])
e = array([2,2,2]) # returns int

# division
c = a/b
f = d//e
print(c)
print(f)

[1 2 3]
[1. 1. 1.]
[ 2  8 12]


In [19]:
# 7.5 Vector Dot Product
from numpy import array

# define first vector
a = array([1,2,3])
print(a)

# define second vector
b = array([1,2,3])
print(b)

# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [23]:
# 7.6 Vector-Scalar Multiplication
from numpy import array

# define vector
a = array([1,2,3])
print(a)

# define scalar
s = 0.5

c = s * a
d = s / a
e = s + a
f = s - a
g = s ** a
h = s // a
i = s % a
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)

[1 2 3]
[0.5 1.  1.5]
[0.5        0.25       0.16666667]
[1.5 2.5 3.5]
[-0.5 -1.5 -2.5]
[0.5   0.25  0.125]
[0. 0. 0.]
[0.5 0.5 0.5]


In [27]:
'''7.7 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Create one example using each operation using your own small array data.
ˆ Implement each vector arithmetic operation manually for vectors defined as lists.
ˆ Search machine learning papers and find 1 example of each operation being used.
If you explore any of these extensions, I’d love to know.'''

from numpy import array
X = array([0.01,0.02,0.03,0.04,0.05])
s = 100

print(X + s, '\n', s - X, '\n', X * s, '\n', X / s)

# ˆ Search machine learning papers and find 1 example of each operation being used.
# All the operations use in ML algorithms such as Random Forest, kNN, Naive Bayes' and mostly SVM 

[100.01 100.02 100.03 100.04 100.05] 
 [99.99 99.98 99.97 99.96 99.95] 
 [1. 2. 3. 4. 5.] 
 [0.0001 0.0002 0.0003 0.0004 0.0005]
