In [8]:
# 8.3 Vector L1 Norm L1(V) = ||v||1 => Manhattan norm
# ||v||1 = |a1| + |a2| + |a3|  => Manhattan distance from the origin of the vector space
# vector L1 norm
'''The L1 norm is often used when fitting machine learning algorithms as a regularization
method, e.g. a method to keep the coefficients of the model small, and in turn, the model less
complex.'''
from numpy import array
from numpy.linalg import norm

# define vector
a = array([1,2,3])
print(a)

# calculate L1 norm
l1 = norm(a,1)
print(l1)

# 8.4 Vector L2 Norm
# L2(v) = ||v||2
# The L2 norm is calculated as
# the square root of the sum of the squared vector values.
# vector L2 norm
'''By far, the L2 norm is more commonly used than other vector norms in machine learning.'''
from numpy import array
from numpy.linalg import norm

# define vector
a = array([1,2,3])
print(a)

# calculate L2 norm = sqrt[|a1| + |a2| + |a3| ]
l2 = norm(a) # => L2 norm can caluclate using default parameters
print(l2)

# 8.5 Vector Max Norm
# The max norm is calculated as returning the maximum value of the vector, hence the name.
'''Max norm is also used as a regularization in machine learning, such as on neural network
weights, called max norm regularization.'''
from math import inf
from numpy import array
from numpy.linalg import norm

# define vector
a = array([1,2,3])
print(a)
maxnorm = norm(a, inf) # => pass inf parameter to get maximum value of the vector
print(maxnorm)

[1 2 3]
6.0
[1 2 3]
3.7416573867739413
[1 2 3]
3.0


In [12]:
'''8.6 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Create one example using each operation using your own small array data.
ˆ Implement each operation manually for vectors defined as lists of lists.
ˆ Search machine learning papers and find 1 example of each operation being used.'''
X = array([6,12,18,24,30])
print(X)

l1 = norm(X, 1)
l2 = norm(X)
maxnorm = norm(X, inf)
# L1 norm
print(l1,'\n',l2,'\n',maxnorm)

# Search machine learning papers and find 1 example of each operation being used.
# https://towardsdatascience.com/l1-and-l2-regularization-methods-ce25e7fc831c
# A regression model that uses L1 regularization technique is called Lasso Regression 
# and model which uses L2 is called Ridge Regression.
'''Ridge regression adds “squared magnitude” of coefficient as penalty term to the loss function.
Lasso Regression (Least Absolute Shrinkage and Selection Operator) adds “absolute value of magnitude” 
of coefficient as penalty term to the loss function.'''

[ 6 12 18 24 30]
90.0 
 44.49719092257398 
 30.0
