In [7]:
# 9.3 Defining a Matrix
# create matrix
from numpy import array
A = array([[1,2,3],
         [4,5,6]])
print(A)

# 9.4.1 Matrix Addition
from numpy import array

# define first matrix
A = array([[1,2,3],
           [4,5,6]])
print(A)

# define second matrix
B = array([[1,2,3],
         [4,5,6]])
print(B)

# add matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [9]:
# 9.4.2 Matrix Subtraction
from numpy import array

# define first matrix
A = array([[1,2,3],
          [4,5,6]])

# define second matrix
B = array([[0.5,0.5,0.5],
          [0.5,0.5,0.5]])

# add matrices
C = A - B
print(C)

[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [11]:
# 9.4.3 Matrix Multiplication (Hadamard Product)
# C = A ◦ B
# matrix hadamard product
from numpy import array

# define first matrix
A = array([[1,2,3],
          [4,5,6]])
print(A)

# define second matrix
B = array([[1,2,3],
          [4,5,6]])
print(B)

# multiply matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [14]:
# 9.4.4 Matrix Division
# One matrix can be divided by another matrix with the same dimensions.
# matrix division
from numpy import array

# define first matrix
A = array([[1,2,3],
          [4,5,6]])
print(A)

# define second matrix
B = array([[1,2,3],
          [4,5,6]])
print(B)

# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# 9.5 Matrix-Matrix Multiplication
# Matrix multiplication, also called the matrix dot product is more complicated than the previous
# operations and involves a rule as not all matrices can be multiplied together.
# C = A · B
'''Matrix A has the dimensions m rows and n columns and matrix B has the
dimensions n and k. The n columns in A and n rows in B are equal. The result is a new matrix
with m rows and k columns.
C(m, k) = A(m, n) · B(n, k)'''
# matrix dot product
from numpy import array

# define first matrix
A = array([[1,2],
          [3,4],
          [5,6]])

# define second matrix
B = array([[1,2],
          [3,4]])

# multiply matrices
C = A.dot(B)
print(C)

# multiply matrices using @ operater (Python 3.5)
D = A @ B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


In [25]:
# 9.6 Matrix-Vector Multiplication
'''A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that the number of columns in the matrix must equal the number of
items in the vector. As with matrix multiplication, the operation can be written using the dot
notation. Because the vector only has one column, the result is always a vector.'''
# c = A · v
# matrix-vector multiplication
from numpy import array

# define matrix
A = array([[1,2],
          [3,4],
          [5,6]])
print(A, '\n')

# define vector
B = array([0.5,0.5])
print(B, '\n')

# multiply
C = A.dot(B)
print(C, '1col')

# multiply matrices using @ operater (Python 3.5)
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]] 

[0.5 0.5] 

[1.5 3.5 5.5] 1col
[1.5 3.5 5.5]


In [28]:
# 9.7 Matrix-Scalar Multiplication
# C = A · b
from numpy import array

# define matrix
A = array([[1,2],[3,4], [5,6]])
print(A)

# define scalar 
b = 0.5
print(b)

# multiply
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [39]:
'''9.8 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Create one example using each operation using your own small array data.
ˆ Implement each matrix arithmetic operation manually for matrices defined as lists of lists.
ˆ Search machine learning papers and find 1 example of each operation being used.'''
from numpy import array

X = array([[11,22],
         [33,44],
         [55,66]])

y = array([[0.11,0.22],
         [0.33, 0.44],
         [0.55, 0.66]])

v = array([3,3])

s = 10000

# addition
Z = X + y
print(Z)

# substraction 
A = X - y
print(A)

# multiplication # matrix hadamard product
B = X * y
print(B)

# division
C = X / y
print(C)

# matrix-vector multiplication 
D = X.dot(v)
print(D)

# matrix scalar multiplication
E = X.dot(s)
print(E)

[[11.11 22.22]
 [33.33 44.44]
 [55.55 66.66]]
[[10.89 21.78]
 [32.67 43.56]
 [54.45 65.34]]
[[ 1.21  4.84]
 [10.89 19.36]
 [30.25 43.56]]
[[100. 100.]
 [100. 100.]
 [100. 100.]]
[ 99 231 363]
[[110000 220000]
 [330000 440000]
 [550000 660000]]
