In [6]:
# 4.2 NumPy N-dimensional Array
# create array
from numpy import array

# create array
l = [1.0,2.0,3.0]
a = array(l)

# display array
print(a)

# display array shape
print(a.shape)

# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [13]:
# 4.3 Functions to Create Arrays
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

# create zeros array
from numpy import zeros
a = zeros([3,5])
print(a)

# create ones array
from numpy import ones
a = ones([1,5])
print(a)

[[-2.31584178e+077 -2.31584178e+077  5.43472210e-323]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


In [19]:
# 4.4 Combining Arrays
# create array with vstack
from numpy import array
from numpy import vstack

# create first array
a = [1,2,3]
b = [4,5,6]

c = vstack([a, b])
print(c)
print(c.shape)

# create array with hstack
from numpy import array
from numpy import hstack

a = [1,2,3]
b = [4,5,6]

c = hstack([a, b])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [59]:
# 4.5 Extensions
'''This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Experiment with the different ways of creating arrays to your own sizes or with new data.
ˆ Locate and develop an example for 3 additional NumPy functions for creating arrays.
ˆ Locate and develop an example for 3 additional NumPy functions for combining arrays.
If you explore any of these extensions, I’d love to know.'''

# Experiment with the different ways of creating arrays to your own sizes or with new data.
a = [1,2,3,4,5]
b = [6,7,8,9,10]

from numpy import empty_like
c = empty_like([a, b])
print(c)

from numpy import ones_like
d = ones_like([a, b])
print(d)

from numpy import zeros_like
e = zeros_like([a, b])
print(e)

from numpy import empty
f = empty([1,2])
print(f)

from numpy import full
g = full((5, 5), 10)
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[5.73021895e-300 3.76505858e-047]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
